# Generated by Django 4.0.2 on 2026-05-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('source_language', models.CharField(blank=True, max_length=12)),
                ('target_language', models.CharField(default='Russian', max_length=64)),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('processing', 'Обработка'), ('done', 'Готово'), ('failed', 'Ошибка')], default='queued', max_length=16)),
                ('original_srt', models.TextField(blank=True)),
                ('translated_srt', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
